make axp192 led settings in ttgobeam10.h to controll led behavior
cyberman54/ESP32-Paxcounter pull request #683
Opened 2020-12-11 15:07 UTC by hekopath

2020-12-15 19:12 UTC, cyberman54 requested changes
Thanks for your PR! We should add this feature. Please see comments in code.

2020-12-15 19:12 UTC, cyberman54 commented on src/power.cpp
> +    #endif
Why not

```
#ifdef PMU_LED_RUN_MODE
pmu.setChgLEDMode(PMU_LED_SLEEP_MODE);
#else
pmu.setChgLEDMode(AXP20X_LED_OFF);
#endif
```

?

2020-12-15 19:12 UTC, cyberman54 commented on src/power.cpp
> +    pmu.setChgLEDMode(PMU_LED_RUN_MODE);
Why not

```
#ifdef PMU_LED_RUN_MODE
pmu.setChgLEDMode(PMU_LED_RUN_MODE);
#else
pmu.setChgLEDMode(AXP20X_LED_LOW_LEVEL);
#endif
```
?

2020-12-16 22:10 UTC, hekopath commented on src/power.cpp
> +    #endif
Propably the more coherent solution.

2020-12-16 22:10 UTC, hekopath commented on src/power.cpp
> +    pmu.setChgLEDMode(PMU_LED_RUN_MODE);
Propably the more coherent solution.

2020-12-17 13:03 UTC, cyberman54 commented
Manually merged to development branch.

2020-12-17 13:03 UTC, closed without merging